// src/lib/components/InputBar.tsx
import { useState } from 'preact/hooks'
import { invoke } from '@tauri-apps/api/core'
import { activeTab, tabStore } from '$lib/stores/tabs'
import { hexStringToBytes } from '$lib/utils/hex'
import { t } from '$lib/i18n'

export function InputBar() {
  const [inputValue, setInputValue] = useState('')
  const [inputMode, setInputMode] = useState<'text' | 'hex'>('text')
  const [sending, setSending] = useState(false)
  const tab = activeTab.value

  async function handleSend() {
    if (!tab.isConnected || !inputValue.trim()) return
    setSending(true)
    try {
      let bytes: number[] = inputMode === 'hex' ? hexStringToBytes(inputValue) : Array.from(new TextEncoder().encode(inputValue))
      await invoke('write_data', { data: bytes })
      tabStore.addLine(tab.id, 'tx', bytes)
      setInputValue('')
    } catch (e) { console.error('Send error:', e) }
    finally { setSending(false) }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend() }
  }

  return (
    <div class="flex items-center gap-2 p-2 border-t border-base-300 bg-base-200/50">
      <div class="join">
        <button class={`btn btn-xs join-item ${inputMode === 'text' ? 'btn-active' : ''}`} onClick={() => setInputMode('text')}>{t('input.text')}</button>
        <button class={`btn btn-xs join-item ${inputMode === 'hex' ? 'btn-active' : ''}`} onClick={() => setInputMode('hex')}>{t('input.hex')}</button>
      </div>
      <input type="text" class="input input-sm flex-1 font-mono" placeholder={inputMode === 'hex' ? t('input.placeholder.hex') : t('input.placeholder.text')} value={inputValue} onInput={(e) => setInputValue((e.target as HTMLInputElement).value)} onKeyDown={handleKeydown} disabled={!tab.isConnected} />
      <button class="btn btn-sm btn-primary" disabled={!tab.isConnected || sending || !inputValue.trim()} onClick={handleSend}>
        {sending && <span class="loading loading-spinner loading-sm"></span>}
        {t('input.send')}
      </button>
    </div>
  )
}

// src/lib/components/InputBar.svelte
<script lang="ts">
  import { invoke } from '@tauri-apps/api/core';
  import { connection } from '$lib/stores/connection';
  import { terminal } from '$lib/stores/terminal';
  import { hexStringToBytes } from '$lib/utils/hex';

  let inputValue = $state('');
  let inputMode = $state<'text' | 'hex'>('text');
  let sending = $state(false);

  async function handleSend() {
    if (!$connection.isConnected || !inputValue.trim()) return;

    sending = true;
    try {
      let bytes: number[];
      if (inputMode === 'hex') {
        bytes = hexStringToBytes(inputValue);
      } else {
        bytes = Array.from(new TextEncoder().encode(inputValue));
      }

      await invoke('write_data', { data: bytes });
      terminal.addLine('tx', bytes);
      inputValue = '';
    } catch (e) {
      console.error('Send error:', e);
    } finally {
      sending = false;
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  }
</script>

<div class="flex items-center gap-2 p-2 border-t border-base-300 bg-base-200/50">
  <div class="join flex-1">
    <button
      class="btn btn-xs join-item"
      class:btn-active={inputMode === 'text'}
      onclick={() => inputMode = 'text'}
    >Text</button>
    <button
      class="btn btn-xs join-item"
      class:btn-active={inputMode === 'hex'}
      onclick={() => inputMode = 'hex'}
    >HEX</button>
  </div>

  <input
    type="text"
    class="input input-sm flex-1 font-mono"
    placeholder={inputMode === 'hex' ? 'Hex: 48 65 6C 6C 6F' : 'Mesajınızı yazın...'}
    bind:value={inputValue}
    onkeydown={handleKeydown}
    disabled={!$connection.isConnected}
  />

  <button
    class="btn btn-sm btn-primary"
    disabled={!$connection.isConnected || sending || !inputValue.trim()}
    onclick={handleSend}
  >
    {#if sending}
      <span class="loading loading-spinner loading-sm"></span>
    {/if}
    Send
  </button>
</div>
